baseURL = "https://username.github.io/blog-lap-trinh/"
languageCode = 'vi'
title = 'Blog Lập Trình Mạng - [CORTIS]'
theme = 'PaperMod'

[params]
	author = 'Nguyễn Thị Thanh Thảo'
	description = 'Blog chia sẻ về lập trình mạng, Java và JavaScript.'
	# Custom CSS (file placed under assets/css/custom.css)
	customCSS = ['css/custom.css']
	# Contact information
	contact_email = 'felicia.nguyenthanh@gmail.com'
	contact_phone = '0899923998'
	profileImage = 'images/martin_1.jpg'

	[params.social]
	  facebook = ''
	  instagram = ''
	  x = ''
	  linkedin = ''

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[[menu.main]]
	name = 'Home'
	url = '/'
	weight = 1

[[menu.main]]
	name = 'Blog'
	url = '/posts/'
	weight = 2

[[menu.main]]
	name = 'Profile'
	url = '/about/'
	weight = 3

[[menu.main]]
	name = 'Contact'
	url = '/contact/'
	weight = 4
